.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "BITCOINJS" "1" "February 2012" "" ""
.
.SH "NAME"
\fBbitcoinjs\fR \-\- BitcoinJS commandline utility
.
.SH "SYNOPSIS"
.
.nf
bitcoinjs <command> [args]
.
.fi
.
.SH "DESCRIPTION"
bitcoinjs is the command line toold for bitcoinjs\-server\. It\'s made up
of modules, similar to the way git or npm are set up\.
.
.P
It\'s main job at the moment is running and controlling the
bitcoinjs\-server daemon\.
.
.SH "USAGE"
.
.IP "\(bu" 4
run:
Run the BitcoinJS daemon in the foreground\. See \fBbitcoinjs help
run\fR\|\.
.
.IP "\(bu" 4
start:
Start BitcoinJS as a daemon in the background\. See \fBbitcoinjs help
start\fR\|\.
.
.IP "\(bu" 4
stop:
Stop the BitcoinJs daemon\. See \fBbitcoinjs help stop\fR\|\.
.
.IP "\(bu" 4
restart:
Restart BitcoinJS daemon\. See \fBbitcoinjs help restart\fR\|\.
.
.IP "\(bu" 4
list:
List currently running instances of BitcoinJS\. See \fBbitcoinjs help
list\fR\|\.
.
.IP "\(bu" 4
db\-reset
Removes all tables from the database\. See \fBbitcoinjs help db\-reset\fR\|\.
.
.IP "\(bu" 4
db\-drop
Drops the database\. This function is slightly slower than db\-reset,
because the allocated hard drive space is being freed up\. See \fBbitcoinjs help db\-drop\fR\|\.
.
.IP "\(bu" 4
bch\-import
Import the block chain from data files\. See \fBbitcoinjs help
bch\-import\fR\|\.
.
.IP "\(bu" 4
bch\-export
Export the block chain data from the database into a series of dump
files\. See \fBbitcoinjs help bch\-export\fR\|\.
.
.IP "\(bu" 4
test:
Executes the BitcoinJS unit tests, powered by VowsJS\. By default the
\-\-spec format is used\. Other available formats are XUnit, JSON and
dot matrix\. See \fBbitcoinjs help test\fR\|\.
.
.IP "\(bu" 4
setup:
Installs the dependencies for a mod\. See the mods/ folder in your
bitcoinjs installation for information on what mods are available\.
.
.IP "" 0
.
.SH "BUGS"
When you find issues or to request new features, please report them:
.
.IP "\(bu" 4
web: \fIhttps://github\.com/bitcoinjs/bitcoinjs\-server/issues\fR
.
.IP "" 0
