.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "BITCOINJS\-RESTART" "1" "August 2011" "" ""
.
.SH "NAME"
\fBbitcoinjs-restart\fR \-\- restart daemon
.
.SH "SYNOPSIS"
.
.nf
bitcoinjs restart [<id>]
.
.fi
.
.SH "OPTIONS"
.
.IP "\(bu" 4
<id>:
The <id> of the process to restart\. See \fBbitcoinjs help list\fR\|\.
.
.IP "" 0
.
.SH "DESCRIPTION"
This command will restart the BitcoinJS daemon\. You can provide an
optional <id> arguments to refer to a specific process as displayed \fBbitcoinjs list\fR, but this is normally not necessary\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
bitcoinjs\-run(1)
.
.IP "\(bu" 4
bitcoinjs\-start(1)
.
.IP "\(bu" 4
bitcoinjs\-stop(1)
.
.IP "\(bu" 4
bitcoinjs\-list(1)
.
.IP "" 0
