.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "BITCOINJS\-RUN" "1" "August 2011" "" ""
.
.SH "NAME"
\fBbitcoinjs-run\fR \-\- run daemon in foreground
.
.SH "SYNOPSIS"
.
.nf
bitcoinjs run [\-\-testnet | \-\-livenet] [<args>]
.
.fi
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-c\fR <file>, \fB\-\-config\fR=<file>:
Path to config file\.
.
.IP "\(bu" 4
\fB\-\-connect\fR=<setting>:
Changes the network connection mode for this node\.
.
.IP
Valid values are:
.
.IP
\fIlocalhost:8333\fR:
Connect to a single node (and allow no other connections)\. You can
also enter multiple hosts, separated by commas\.
.
.IP
\fIp2p\fR:
Use bootstrapping to connect to the open peer\-to\-peer network\.
.
.IP
\fIauto\fR:
Check if localhost:8333 is available and if so, disable
bootstrapping and use localhost as the only connection\. Otherwise
use p2p mode\. (default)
.
.IP "\(bu" 4
\fB\-\-addnode\fR:
Add a node to the pool of known peers\.
.
.IP "\(bu" 4
\fB\-\-forcenode\fR:
Force maintaining a connection to this node always\. This
option override any settings from \-\-connect, meaning even if
the node is in single connection mode it will maintain connections
to \-\-forcenode peers in addition\.
.
.IP "\(bu" 4
\fB\-\-nolisten\fR:
Disable incoming connections\.
.
.IP "\(bu" 4
\fB\-\-livenet\fR:
Connect to the main Bitcoin blockchain (default)\.
.
.IP "\(bu" 4
\fB\-\-testnet\fR:
Connect to the test network
.
.IP "\(bu" 4
\fB\-\-port\fR=<port>:
Port to listen for incoming peer\-to\-peer connections\.
.
.IP "\(bu" 4
\fB\-\-rpcuser\fR=<username>:
Username for JSON\-RPC connections\.
.
.IP "\(bu" 4
\fB\-\-rpcpassword\fR=<password>:
Password for JSON\-RPC connections\.
.
.IP "\(bu" 4
\fB\-\-rpcport\fR=<port>:
Listen for JSON\-RPC connections on <port> (default: 8432)
.
.IP "\(bu" 4
\fB\-\-netdbg\fR:
Enable networking debug messages\.
.
.IP "\(bu" 4
\fB\-\-bchdbg\fR:
Enable block chain debug messages\.
.
.IP "\(bu" 4
\fB\-\-rpcdbg\fR:
Enable JSON RPC debug messages\.
.
.IP "\(bu" 4
\fB\-\-scrdbg\fR:
Enable script parser/interpreter debug messages\.
.
.IP "\(bu" 4
\fB\-h\fR, \fB\-\-help\fR:
Inline command help\.
.
.IP "" 0
.
.SH "DESCRIPTION"
Runs the BitcoinJS daemon in the foreground\. Useful for testing and
for the initial blockchain download\.